<?xml version="1.0" encoding="utf-8"?><Database Name="u2xMain" Class="DAODataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=184.168.194.78;Initial Catalog=u2xMain;Persist Security Info=True;User ID=fbapereira" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="u2xMainConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="fbapereira.tbl_ivc_agenda" Member="Agendas">
    <Type Name="Agenda">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="title" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="description" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
</Database>